on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write

name: Build and Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build Gem
        run: gem build bay_jekyll_theme.gemspec

      - name: Release Gem
        run: gem push bay_jekyll_theme-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}